name: LLBDSBot

on:
  # Triggers the workflow to run every hour
  schedule:
    - cron: 0 * * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DISCORD_WEBHOOK_LLBDS: ${{ secrets.DISCORD_WEBHOOK_LLBDS }}
  
jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: bots
    - name: Run LLBDS-Bot Shell Script
      run: |
         bash .scripts/llbdsbot.sh
      shell: bash
